CREATE DATABASE GTM_MARKET_ENTRY;
USE GTM_MARKET_ENTRY;
SHOW TABLES;
SELECT COUNT(*) FROM UPI_DATA;
SELECT COUNT(*) FROM POPULATION;
SELECT COUNT(*) FROM STATE_DATA;
SELECT COUNT(*) FROM COMPETITORS;
SELECT COUNT(*) FROM BNPL_MARKET;
SELECT COUNT(*) FROM CUSTOMER_SEGMENTS;
SELECT COUNT(*) FROM MERCHANT_SEGMENTS;
SELECT COUNT(*) FROM UNIT_ECONOMICS;
SELECT COUNT(*) FROM RBI_DATA;
SELECT COUNT(*) FROM RISK_REGULATION;

/*State Market Ranking*/
SELECT STATE, POPULATION_M
FROM STATE_DATA
ORDER BY POPULATION_M DESC;

/* Top 5 Launch Markets*/
SELECT STATE,POPULATION_M
FROM STATE_DATA
ORDER BY POPULATION_M DESC
LIMIT 5;

/* State Opportunity Index*/
SELECT STATE, POPULATION_M,
ROUND(POPULATION_M /(SELECT AVG(POPULATION_M)FROM STATE_DATA),2) AS OPPORTUNITY_INDEX
FROM STATE_DATA
ORDER BY OPPORTUNITY_INDEX DESC;

/*Launch Priority Matrix*/
SELECT STATE, POPULATION_M,
ROUND(POPULATION_M /(SELECT AVG(POPULATION_M)FROM STATE_DATA),2) AS OPPORTUNITY_SCORE,
CASE
WHEN POPULATION_M >=100 THEN 'PHASE 1'
WHEN POPULATION_M >=70 THEN 'PHASE 2'
ELSE 'PHASE 3'
END AS LAUNCH_PHASE
FROM STATE_DATA
ORDER BY OPPORTUNITY_SCORE DESC;

/*Revenue Potential by State*/
SELECT STATE,POPULATION_M,
ROUND(POPULATION_M * 0.05,2) AS TARGET_USERS_M,
ROUND(POPULATION_M * 0.05 * 700,0) AS POTENTIAL_REVENUE_MN
FROM STATE_DATA
ORDER BY POTENTIAL_REVENUE_MN DESC;

/*Total Competitors*/
SELECT COUNT(*) AS TOTAL_COMPETITORS
FROM COMPETITORS;

/*Largest Competitor*/
SELECT COMPETITOR, USERS_M
FROM COMPETITORS
ORDER BY USERS_M DESC;

/*Largest Merchant Network*/
SELECT COMPETITOR, MERCHANTS
FROM COMPETITORS
ORDER BY MERCHANTS DESC;

/*BNPL vs EMI Competition*/
SELECT TYPE,
COUNT(*) AS TOTAL_PLAYERS
FROM COMPETITORS
GROUP BY TYPE;

/*Average Competitor User Base*/
SELECT ROUND(AVG(USERS_M),2) AS AVG_USERS_M
FROM COMPETITORS;

/*Competitor Ranking*/
SELECT COMPETITOR,USERS_M,RANK() OVER(ORDER BY USERS_M DESC) AS USER_RANK
FROM COMPETITORS;

/*Market Share Analysis*/
SELECT COMPETITOR,USERS_M,
ROUND(USERS_M *100.0 /SUM(USERS_M) OVER(),2) AS MARKET_SHARE
FROM COMPETITORS
ORDER BY MARKET_SHARE DESC;

/*White Space Analysis*/
SELECT COMPETITOR,USERS_M,MERCHANTS,
ROUND(USERS_M / MERCHANTS,2) AS USERS_PER_MERCHANT
FROM COMPETITORS
ORDER BY USERS_PER_MERCHANT DESC;

/*Competitive Threat Analysis*/
SELECT COMPETITOR,USERS_M,MERCHANTS,
CASE
WHEN USERS_M > 50
THEN 'HIGH THREAT'
WHEN USERS_M > 15
THEN 'MEDIUM THREAT'
ELSE 'LOW THREAT'
END AS COMPETITIVE_THREAT
FROM COMPETITORS
ORDER BY USERS_M DESC;

/* HHI Market Concentration Analysis */
WITH MARKET_SHARE AS (SELECT COMPETITOR,USERS_M,
USERS_M / SUM(USERS_M) OVER() AS SHARE
FROM COMPETITORS)
SELECT ROUND(SUM(POWER(SHARE,2)) * 10000,0) AS HHI_SCORE,
CASE
WHEN ROUND(SUM(POWER(SHARE,2)) * 10000,0) < 1500
THEN 'COMPETITIVE MARKET'
WHEN ROUND(SUM(POWER(SHARE,2)) * 10000,0) BETWEEN 1500 AND 2500
THEN 'MODERATELY CONCENTRATED'
ELSE 'HIGHLY CONCENTRATED'
END AS MARKET_STRUCTURE
FROM MARKET_SHARE;

/*BNPL Market Growth Projection*/
SELECT METRIC,VALUE
FROM BNPL_MARKET
WHERE METRIC LIKE '%TAM%';

/*BNPL Market Summary*/
SELECT METRIC,VALUE
FROM BNPL_MARKET;

/*UPI Adoption Funnel*/
SELECT METRIC, VALUE
FROM UPI_DATA;

/*Competitor Strength Mapping*/
SELECT COMPETITOR,STRENGTH
FROM COMPETITORS
ORDER BY USERS_M DESC;

/*TAM SAM SOM*/
SELECT'TAM' AS MARKET_LEVEL,45000 AS VALUE_USD_M
UNION ALL 
SELECT
'SAM',12000
UNION ALL
 SELECT
'SOM_YEAR_1',40
UNION ALL
SELECT 'SOM_YEAR_3',324
UNION ALL
SELECT'SOM_YEAR_5',1134;

/*Executive GTM Dashboard*/
SELECT (SELECT COUNT(*) FROM COMPETITORS) AS TOTAL_COMPETITORS,
(SELECT MAX(USERS_M)
FROM COMPETITORS) AS MARKET_LEADER_USERS_M,
(SELECT MAX(POPULATION_M)
FROM STATE_DATA) AS LARGEST_STATE_POPULATION_M,
(SELECT AVG(USERS_M) 
FROM COMPETITORS) AS AVG_COMPETITOR_USERS_M;

/*State Attractiveness Score*/
SELECT STATE, POPULATION_M,
DENSE_RANK() OVER(ORDER BY POPULATION_M DESC) AS MARKET_RANK
FROM STATE_DATA;

/*Competitor Market Share*/
SELECT COMPETITOR,USERS_M,
ROUND(USERS_M * 100.0 /SUM(USERS_M) OVER(),2) AS MARKET_SHARE_PCT
FROM COMPETITORS ORDER BY MARKET_SHARE_PCT DESC;

/*Competitive Concentration (HHI)*/
WITH SHARES AS (SELECT USERS_M /SUM(USERS_M) OVER() AS SHARE
FROM COMPETITORS)
SELECT ROUND(SUM(POWER(SHARE,2))*10000,0)
AS HHI_SCORE FROM SHARES;


/*Launch Priority Ranking*/
SELECT STATE,POPULATION_M,
ROW_NUMBER() OVER(ORDER BY POPULATION_M DESC) AS LAUNCH_PRIORITY
FROM STATE_DATA;

/* EXECUTIVE GTM DECISION */
SELECT'INDIA BNPL MARKET' AS MARKET,
(SELECT COUNT(*) FROM COMPETITORS)
AS TOTAL_COMPETITORS,
(SELECT MAX(POPULATION_M)
FROM STATE_DATA)
AS LARGEST_STATE_POP_M,
(SELECT MAX(USERS_M)
FROM COMPETITORS)
AS MARKET_LEADER_USERS_M,
'YES' AS LARGE_ADDRESSABLE_MARKET,
'YES' AS DIGITAL_INFRASTRUCTURE_READY,
'YES' AS COMPETITIVE_WHITESPACE_EXISTS,
'ENTER MARKET' AS FINAL_RECOMMENDATION;